version: '2'

services:
   db:
     image: mysql:5.7
     volumes:
       - db_data:/var/lib/mysql
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: root
       MYSQL_DATABASE: memedb
       MYSQL_USER: root
       MYSQL_PASSWORD: root

   site:
     depends_on:
       - db
     image: alpacamybags/memedb
     ports:
       - "80:80"
     restart: always
     environment:
       MEMEDB_DB_HOST: db:3306
       MEMEDB_DB_USER: root
       MEMEDB_DB_PASSWORD: root
volumes:
    db_data:
